### ISSUE TITLE
0xDjango - Fees are lost if fee growth surpasses user's share value

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#107]
0xDjango

high

# Fees are lost if fee growth surpasses user's share value

## Summary
In `Dispatcher.sol`, when a user withdraws LP, the fees that are owed to them is subtracted from their current LP balance. In the case where the position’s earned fees outweigh the position’s current shares, claiming fees will cause a revert due to underflow.

If trading volume within the UniV3 position ticks are substantial, it can be expected that fees can outweigh initial value within a reasonable amount of time (1 to 2 years).

## Vulnerability Detail
Quite simply, since the fees are subtracted from the user's LP balance, if the fees amount to more than the initial value of the deposit, fee withdrawal will revert due to underflow.

In order to withdraw the original LP value, the user must withdraw while declining receiving the fees.

## Impact
- Loss of earned fees

## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/82a234a5c2c1fc1921c63265a9349b71d84675c4/concentrator/contracts/Dispatcher.sol#L236
```solidity
    function withdraw(uint256 pid, uint256 amount, uint256 deviationBP) external checkPid(pid) {
        ...

        } else if (amount < user.shares) {
            uint256 lpAmount;
            {
                (uint256 fee0, uint256 fee1) = _calcFees(feesGrow, user);
                lpAmount = _estimateWithdrawalLp(reserve0, reserve1, _totalSupply, fee0, fee1);
            }
            user.shares -= lpAmount;
```

## Tool used
Manual Review

## Recommendation
Do not subtract fees from LP balance.

**Comment by eliteWalrus4164** [comment]
Escalate

Some of the issues attached as duplicates here are invalid or not duplicates:
#6 : Valid but not a duplicate, this demonstrates how it is not possible to claim fees from multipool LP tokens which are not staked inside a Dispatcher, and is similar to #128

#12: 
Not sure if the watson got confused by his own reasoning, but these lines cannot underflow:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L240-L241
(the ternary before the assignement is actually a precaution to avoid underflow)

#20:
Not valid, all the fees are withdrawn for the user in the case of a partial withdrawal because `feeDebt` variables are set to latest accShare:

https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L243-L244

And if the user only withdraws part of the fees, he wouldn't be able to claim the rest on a subsequent withdrawal

#35:
The watson claims there is a loss of precision because multiplication before division rule is not implemented in `_estimateLpWithdrawal`. It is simply not correct:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L148
 
#83: Valid and duplicate of #6 and #128

#100: Valid and duplicate of this issue

#125: Invalid, same reasoning as with #20, the fees are withdrawn because the `feeDebt` variables are also reset in deposit

**Comment by sherlock-admin** [comment]
> Escalate
> 
> Some of the issues attached as duplicates here are invalid or not duplicates:
> #6 : Valid but not a duplicate, this demonstrates how it is not possible to claim fees from multipool LP tokens which are not staked inside a Dispatcher, and is similar to #128
> 
> #12: 
> Not sure if the watson got confused by his own reasoning, but these lines cannot underflow:
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L240-L241
> (the ternary before the assignement is actually a precaution to avoid underflow)
> 
> #20:
> Not valid, all the fees are withdrawn for the user in the case of a partial withdrawal because `feeDebt` variables are set to latest accShare:
> 
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L243-L244
> 
> And if the user only withdraws part of the fees, he wouldn't be able to claim the rest on a subsequent withdrawal
> 
> #35:
> The watson claims there is a loss of precision because multiplication before division rule is not implemented in `_estimateLpWithdrawal`. It is simply not correct:
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Dispatcher.sol#L148
>  
> #83: Valid and duplicate of #6 and #128
> 
> #100: Valid and duplicate of this issue
> 
> #125: Invalid, same reasoning as with #20, the fees are withdrawn because the `feeDebt` variables are also reset in deposit

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by shealtielanz** [comment]
I agree with what the watson said.
However, the issue #35 is a duplicate of #142. and the rest of what he said i agree to an extent.

**Comment by shealtielanz** [comment]
The watson is correct some of the issues attached are not duplicates
#142 is a duplicate of #35 
And #83 is a valid duplicate of #6

**Comment by Oxdice91** [comment]
The watson is correct, some of the issues attached here are not duplicates
#142 is a duplicate of #35 
And #83 is a valid duplicate of #6

**Comment by fann95** [comment]
The fees cannot be lost because they are part of the LP. The LP becomes more expensive by the amount of fees. It doesn't matter how many fees the pool earns, as your LP will become more expensive for this amount.

**Comment by seerether** [comment]
#20 is a duplicate of the issue - vulnerability arises when amount parameter passed to the function is greater than the user's shares

**Comment by huuducsc** [comment]
> I agree with what the watson said. However, the issue #35 is a duplicate of #142. and the rest of what he said i agree to an extent.

I disagree that issue #35 is a duplicate of #142. They are very different. Issue #35 pertains to precision loss during multiplication before division. I believe it is a duplicate of #133, and should be a non-issue, given that the maximum potential loss amount is only 1-2 LP shares.  However, issue #142 describes a scenario involving fluctuating rate of positions in Uniswap, which results in incorrect `_estimateWithdrawalLp` because of using average calculation.

**Comment by hrishibhat** [comment]
Result:
Invalid
Has duplicates
Agree with the Escalation and the duplicates need to be readjusted. 
Additionally, this issue is not a valid issue based on Sponsor's comment
https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/107#issuecomment-1638823495

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [crimson-rat-reach](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/107/#issuecomment-1634681126): accepted

**Comment by 0xpinky** [comment]
@hrishibhat  issue #125  talks about the deposit , not about fees.. pls check while duplicating.
