### ISSUE TITLE
shealtielanz - Incorrect ratioX196 calculated due to casting.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#120]
shealtielanz

medium

# Incorrect ratioX196 calculated due to casting.

## Summary
the ratioX192 is calculated from the sqrtPriceX96^2 however only one is casted to uint.
## Vulnerability Detail
The issue is in the multipool getAmountOut function.

        uint160 sqrtPriceX96 = TickMath.getSqrtRatioAtTick(avarageTick);
        if (sqrtPriceX96 <= type(uint128).max) {
            uint256 ratioX192 = uint256(sqrtPriceX96) * sqrtPriceX96;
            swappedOut = zeroForOne
                ? FullMath.mulDiv(ratioX192, amountIn, 1 << 192)
                : FullMath.mulDiv(1 << 192, amountIn, ratioX192);
        } else {
            uint256 ratioX128 = FullMath.mulDiv(sqrtPriceX96, sqrtPriceX96, 1 << 64);
            swappedOut = zeroForOne
                ? FullMath.mulDiv(ratioX128, amountIn, 1 << 128)
                : FullMath.mulDiv(1 << 128, amountIn, ratioX128);
        }
here only one sqrtPriceX96 is casted down to uint256 causing truncation that will cause inaccuracies when bit shifting the ratioX192
## Impact
The is the ratioX192 is incorrect this lead to wrong prices and also incorrect amountOut calculated causing loss of funds to users
## Code Snippet
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L826C1-L837C10
## Tool used

Manual Review

## Recommendation
Use the safeCast library and do appropriate casting to the values of sqrtPriceX96.

**Comment by shealtielanz** [comment]
Escalate

I agree with you ser, your point is valid, but that isn't the issue i'm pointing to, the issue here is ----> 
Only one `sqrtPriceX96` is cast to `uint256`.
where 
```solidity
     uint256 ratioX192 = uint256(sqrtPriceX96) * sqrtPriceX96;
```
[Click here](https://github.com/sherlock-audit/2023-06-real-wagmi/blob/82a234a5c2c1fc1921c63265a9349b71d84675c4/concentrator/contracts/Multipool.sol#L828) you can see here that instead of both being cast to `uint256` only one `sqrtPriceX96` is cast, and this can lead to a `potential overflow` If `sqrtPriceX96` is a large value close to the maximum range of `uint128`, casting it to `uint256` might still allow it to fit within the larger data type. However, performing multiplication between the casted `uint256` and the original `uint128` value may result in an overflow if the product exceeds the maximum value that can be represented by `uint256`, Also Casting `sqrtPriceX96` to `uint256` while keeping the other variable as `uint128` may result in a loss of precision or truncation of the decimal places, depending on the size of `sqrtPriceX96`, this loss of precision could impact the accuracy of the subsequent calculations

The fix is straight forward cast the two `sqrtPriceX96` being multiplied to `uint256`.
```solidity
     uint256 ratioX192 = uint256(sqrtPriceX96) * uint256(sqrtPriceX96);
```
A similar issue was reported by Trust_90 in his [rysk Audit](https://www.trust-security.xyz/rysk-audit) M-3 but the issue there is a bit different

this can cause issues when calculating the `ratioX192`, especially when trying to calculate the `swappedOut` , this can be exploited where an attacker is capable of binary exploitation, so leaving the issue as a valid medium is a good option.

This issue is also clearly not  a duplicate of #32 and i ask that the judge look into the findings

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I agree with you ser, your point is valid, but that isn't the issue i'm pointing to, the issue here is ----> 
> Only one `sqrtPriceX96` is cast to `uint256`.
> where 
> ```solidity
>      uint256 ratioX192 = uint256(sqrtPriceX96) * sqrtPriceX96;
> ```
> [Click here](https://github.com/sherlock-audit/2023-06-real-wagmi/blob/82a234a5c2c1fc1921c63265a9349b71d84675c4/concentrator/contracts/Multipool.sol#L828) you can see here that instead of both being cast to `uint256` only one `sqrtPriceX96` is cast, and this can lead to a `potential overflow` If `sqrtPriceX96` is a large value close to the maximum range of `uint128`, casting it to `uint256` might still allow it to fit within the larger data type. However, performing multiplication between the casted `uint256` and the original `uint128` value may result in an overflow if the product exceeds the maximum value that can be represented by `uint256`, Also Casting `sqrtPriceX96` to `uint256` while keeping the other variable as `uint128` may result in a loss of precision or truncation of the decimal places, depending on the size of `sqrtPriceX96`, this loss of precision could impact the accuracy of the subsequent calculations
> 
> The fix is straight forward cast the two `sqrtPriceX96` being multiplied to `uint256`.
> ```solidity
>      uint256 ratioX192 = uint256(sqrtPriceX96) * uint256(sqrtPriceX96);
> ```
> A similar issue was reported by Trust_90 in his [rysk Audit](https://www.trust-security.xyz/rysk-audit) M-3 but the issue there is a bit different
> 
> this can cause issues when calculating the `ratioX192`, especially when trying to calculate the `swappedOut` , this can be exploited where an attacker is capable of binary exploitation, so leaving the issue as a valid medium is a good option.
> 
> This issue is also clearly not  a duplicate of #32 and i ask that the judge look into the findings

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Actually this issue has been raised in other contest, recommend maintaining low severity

Related discussion:

https://github.com/sherlock-audit/2023-06-arrakis-judging/issues/34

**Comment by shealtielanz** [comment]
I strongly but respectfully disagree ser, All the cases of this issue and been noted as a Medium Severity, I don't see why my case should be different. even the issue you reference to was given a medium but  mine is more of an issue since it is been used to calculate the swapedOut(Amount out)

**Comment by c14sh** [comment]
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.10;

contract Arithmetic {
    function convert() external pure returns (uint) {
        uint160 price = type(uint128).max;

        return uint(price) * price;
    }
}
```

**Comment by hrishibhat** [comment]
@c14sh Hi, could you comment on what your code above is implying?

**Comment by c14sh** [comment]
That overflow never happens. There's no such thing like potential overflow.

**Comment by hrishibhat** [comment]
@shealtielanz agreed with the above comment based on the code snippet. 
This seems to be a non issue. Do you have further comments?

**Comment by shealtielanz** [comment]
What he said seems reasonable, although this doesn't match the implementations I've seen on other Protocols, also both of them has to be casted together as I've also seen in other Protocols
Should be a low atleast.
Thank you

**Comment by shealtielanz** [comment]
Also this issue isn't a duplicate of #32 
as there is an actual case of Unsafe downcasting in that #32 that could lead to issues in calculations 
Please check it ser.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Considering this a non-issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [shealtielanz](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/120/#issuecomment-1633057924): rejected
