### ISSUE TITLE
tank - `rebalanceAll` function is not safe from MEV sandwich attack

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#131]
tank

high

# `rebalanceAll` function is not safe from MEV sandwich attack

## Summary
`rebalanceAll` function uses not safe slippage control, the function calculates amountOut from pool TWAP price which leads to the loss of fund from sandwich attacks.
## Vulnerability Detail
in `rebalanceAll` function, the operator can swap tokens in the contract to another tokens to reopen the LP position.
1. let's look at `getAmountOut` function
```solidity
    /**
     * @notice Calculates the estimated amount of token that will be received as output with the specified input amount and current price.
     * @param zeroForOne A boolean to specify if token0(true) or token1(false) is the input currency.
     * @param amountIn The input amount of the token to swap.
     * @return swappedOut The estimated output amount of tokens that will be received based on the current price.
     */
    function getAmountOut(
        bool zeroForOne,
        uint256 amountIn
    ) public view returns (uint256 swappedOut) {
        uint32[] memory secondsAgo = new uint32[](2);
        secondsAgo[0] = twapDuration;
        secondsAgo[1] = 0;
        (int56[] memory tickCumulatives, ) = IUniswapV3Pool(underlyingTrustedPools[500].poolAddress)
            .observe(secondsAgo);
        int24 avarageTick = int24((tickCumulatives[1] - tickCumulatives[0]) / int32(twapDuration));
        uint160 sqrtPriceX96 = TickMath.getSqrtRatioAtTick(avarageTick);
        if (sqrtPriceX96 <= type(uint128).max) {
            uint256 ratioX192 = uint256(sqrtPriceX96) * sqrtPriceX96;
            swappedOut = zeroForOne
                ? FullMath.mulDiv(ratioX192, amountIn, 1 << 192)
                : FullMath.mulDiv(1 << 192, amountIn, ratioX192);
        } else {
            uint256 ratioX128 = FullMath.mulDiv(sqrtPriceX96, sqrtPriceX96, 1 << 64);
            swappedOut = zeroForOne
                ? FullMath.mulDiv(ratioX128, amountIn, 1 << 128)
                : FullMath.mulDiv(1 << 128, amountIn, ratioX128);
        }
    }
```

the function calculates amount out from uniswap v3 pool TWAP, so due to nature of the TWAP if the market is volatile the TWAP will deviate from the pool spot price.
For example, pool ETH-USDC -> current price is 1,800 and then the price spike to 1,900
, so current pool price is 1,900 and the TWAP is 1850

```solidity
/**
     * @dev This function closes all opened positions, swaps desired token to other(if needed) and opens new positions
     *      with new strategy settings
     * @param params Details for the swap
     * */
    function rebalanceAll(RebalanceParams calldata params) external nonReentrant {
    ...
    uint reserve0Before = IERC20(token0).balanceOf(address(this));
        uint reserve1Before = IERC20(token1).balanceOf(address(this));
        if (params.amountIn > 0) {
            _approveToken(params.zeroForOne ? token0 : token1, params.swapTarget, params.amountIn);
            (bool success, ) = params.swapTarget.call(params.swapData);
            ErrLib.requirement(success, ErrLib.ErrorCode.ERROR_SWAPPING_TOKENS);
        }
        uint reserve0 = IERC20(token0).balanceOf(address(this));
        uint reserve1 = IERC20(token1).balanceOf(address(this));
        ErrLib.requirement(
            reserve0 > MINIMUM_AMOUNT && reserve1 > MINIMUM_AMOUNT,
            ErrLib.ErrorCode.INSUFFICIENT_LIQUIDITY
        );
        uint256 amountIn = params.zeroForOne
            ? reserve0Before - reserve0
            : reserve1Before - reserve1;
        ErrLib.requirement(amountIn <= params.amountIn, ErrLib.ErrorCode.AMOUNT_IN_TO_BIG);
        uint256 amountOut = params.zeroForOne
            ? reserve1 - reserve1Before
            : reserve0 - reserve0Before;
        uint256 swappedOut = getAmountOut(params.zeroForOne, amountIn);
        if (amountOut < swappedOut) {
            ErrLib.requirement(
                (swappedOut * maxTwapDeviation) / MAX_WEIGHT_UINT256 >= swappedOut - amountOut,
                ErrLib.ErrorCode.PRICE_SLIPPAGE_CHECK
            );
        }
        ...
    ```
   as you can see from `rebalanceAll` function, the operator specify swap amount, and check slippage with `getAmountOut` function which uses TWAP. If the TWAP is 1850 and the spot price is 1900, at first the `maxTwapDeviation` is 1% plus the deviation from pool current price and TWAP price which around 2.5%, in total it will be 3.5% max loss from swap amount.
## Impact
all users who deposit in this contract may lose some tokens from current price and TWAP price deviation.
## Code Snippet
- 
## Tool used

Manual Review

## Recommendation
@ https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L876C1-L881
adding `amountOutMin` instead of using TWAP
```solidity
ErrLib.requirement(
                amountOut >= params.amountOutMin,
                ErrLib.ErrorCode.PRICE_SLIPPAGE_CHECK
            );
```

**Comment by syjcnss** [comment]
Escalate

This is not a duplicate of #94 and I believe it's invalid.

#94 desribes the problem of slippage in liquidity withdraw&deposit.
This one describes the slippage in swap.

This one assumes a high volatile market and that sandwich bot can profit from the deviation between spot price and TWAP price.

The problem here is that what is the 'true' price in this high volatile market? Which price should be consulted for slippage? The TWAP price? The spot price? Or offchian price?

The Recommendation suggests that an `amountOutMin` should be posted from offchain. But the `amountOutMin` is calculated from the offchian price. The offchian price may come from the TWAP price, the spot price the dex or other price providers. For high volatile market, the same deviation still happens. So it won't improve anything. And there will be much more time lag between the price query, slippage caculation offchain and the swap execution.

So the Recommendation won't fix the problem but will make the problem worse.

To set a slippage, a price must be consulted and the protocol chooses to use the TWAP price at contract execution. This is not perfect but slippage is a problem lies inside ethereum and it is not the responsibility of this protocol to solve this.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This is not a duplicate of #94 and I believe it's invalid.
> 
> #94 desribes the problem of slippage in liquidity withdraw&deposit.
> This one describes the slippage in swap.
> 
> This one assumes a high volatile market and that sandwich bot can profit from the deviation between spot price and TWAP price.
> 
> The problem here is that what is the 'true' price in this high volatile market? Which price should be consulted for slippage? The TWAP price? The spot price? Or offchian price?
> 
> The Recommendation suggests that an `amountOutMin` should be posted from offchain. But the `amountOutMin` is calculated from the offchian price. The offchian price may come from the TWAP price, the spot price the dex or other price providers. For high volatile market, the same deviation still happens. So it won't improve anything. And there will be much more time lag between the price query, slippage caculation offchain and the swap execution.
> 
> So the Recommendation won't fix the problem but will make the problem worse.
> 
> To set a slippage, a price must be consulted and the protocol chooses to use the TWAP price at contract execution. This is not perfect but slippage is a problem lies inside ethereum and it is not the responsibility of this protocol to solve this.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by tapakornl** [comment]
TWAP can be manipulated easier than sending user expected `amountOutMin` from offchain. And it is very unsafe to assume that the arbitrage bot will always arbitrage back to the pool price, eg. recent Rodeo finance (https://twitter.com/immunefi/status/1679269288375451649?s=20), eventhough the hacker buy and wait for ~1.30 minutes to sell back the tokens, no one is arbing the pool back to the normal price

**Comment by syjcnss** [comment]
> TWAP can be manipulated easier than sending user expected amountOutMin from offchain

The point is how is this 'user expected `amountOutMin`' being calculated. For example, to swap 100 ETH to USDC, how should one calculate the `amountOutMin` of USDC? A price source must be consulted to make the calculation. What price source is considered to provide the **safe real price** for a high volatile market?

For attacking TWAP, the attacker cannot predict when the rebalance will happen, they cannot maintain a unreal price and wait for the operator to send the rebalance transaction.

What they can do is to watch the mempool and when they see the rebalance transaction, there will be not time for them to manipulate the TWAP price.

**Comment by tapakornl** [comment]
1. it is invalid to say that **the attacker cannot predict when the rebalance will happen**, cause rebalance usually depends on time or some conditions. What if the attacker can figure that out?
2. why should you try to find the **safe real price** instead you should use the **spot pool price** from off chain (like uniswap does).

**Comment by syjcnss** [comment]
Spot pool price (no matter on chain/off chain) is much more easier to manipulate than TWAP price.

Uniswap could give the user a disadvantage/manipulated spot price in a fluctuant market on the frontend. Uniswap has no intention to prevent user from this. User takes the risk.

**Comment by tapakornl** [comment]
Then why uniswap use spot pool price from off chain then?

**Comment by tapakornl** [comment]
Ok. Let's take ETH-USDC pair as example. We know what the actual price it should be at any moment in time. However, the TWAP of the pool may deviate from the current price. The longer the "twap duration", the higher the deviation. 

This can seem small like 3-10% price deviation depending on the twap duration, but this can also happen on "every" rebalance instance. The point is the loss from using TWAP can have very high deviation, leading to larger losses on every rebalance, which can accumulate to a really large loss for depositors if extrapolated to annually.
The recommended mitigation would be to use offchain slippage control instead of fully relying on on-chain twap, which can have large deviation -- a bigger room for arbitrage

**Comment by syjcnss** [comment]
> We know what the actual price it should be at any moment in time. However, the TWAP of the pool may deviate from the current price.

Actually we don't know. The token price in one's own expectation is also a price source, which is also manipulatable/could be wrong because of fear, greed, lagging in market observation, incorrect market assessment, numerical processing imprecision of human brain, fat-finger, malicious rebalancer, etc. TWAP price, chainlink price, spot price, a price in a cex or a price in one's own mind, only reflects their own opinion of the market in their own way. You can never tell which one is the currently actual price. Every single one can deviate from another one.

**Comment by hrishibhat** [comment]
@ctf-sec

**Comment by ctf-sec** [comment]
> ##

I would have to agree with this escalation after read this report again and the discussion above

there are also some good info in https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/92

but none of this issue has to be with using TWAP price to derive the amountOut, the cost of manipulating TWAP price is high

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the escalation that this low/informational issue. 
> To set a slippage, a price must be consulted and the protocol chooses to use the TWAP price at contract execution. This is not perfect but slippage is a problem lies inside ethereum and it is not the responsibility of this protocol to solve this.

Issue seems to be describing the limitations of swaps with slippage. Do not see a high/medium issue described here.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [syjcnss](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/131/#issuecomment-1634620049): accepted
