### ISSUE TITLE
minhtrng - Incorrect usage of slippage protection params

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#180]
minhtrng

high

# Incorrect usage of slippage protection params

## Summary

The parameters passed as slippage protection are used incorrectly, causing users to overpay.

## Vulnerability Detail

The function `deposit` receives the parameters `amount0Min` and `amount1Min` which are meant to be for slippage protection:

```js
@param amount0Min The minimum amount of token0 required to be deposited.
@param amount1Min The minimum amount of token1 required to be deposited.
```

These parameters are used within `_optimizeAmounts` to recalculate the values for `amount0Desired/amount1Desired`:

```js
//in deposit
(amount0Desired, amount1Desired) = _optimizeAmounts(
    amount0Desired,
    amount1Desired,
    amount0Min,
    amount1Min,
    reserve0,
    reserve1
);

// in _optimizeAmounts
if (reserve0 == 0 && reserve1 == 0) {
    (amount0, amount1) = (amount0Desired, amount1Desired);
} else {
    uint256 amount1Optimal = _quote(amount0Desired, reserve0, reserve1);
    if (amount1Optimal <= amount1Desired) {
        ErrLib.requirement(
            amount1Optimal >= amount1Min,
            ErrLib.ErrorCode.INSUFFICIENT_1_AMOUNT
        );
        (amount0, amount1) = (amount0Desired, amount1Optimal);
    } else {
        ...
```

`_quote` uses a UniV2 sort of calculation to calculate the amountOut for an input amount:

```js
//WARDEN-NOTE: this is the quote function as found in UniswapV2Library.sol
function _quote(
    uint256 amountA,
    uint256 reserveA,
    uint256 reserveB
) private pure returns (uint256 amountB) {
    ErrLib.requirement(amountA > 0, ErrLib.ErrorCode.INSUFFICIENT_AMOUNT);
    ErrLib.requirement(reserveA > 0 && reserveB > 0, ErrLib.ErrorCode.INSUFFICIENT_LIQUIDITY);
    amountB = (amountA * reserveB) / reserveA;
}
```

However, using the results of this calculation as the "optimal amount" is false, as it does not represent the actual amount required when minting positions across the different v3 pools.

## Impact

Slippage protection does not work as intended

## Code Snippet

https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L459-L466

## Tool used

Manual Review

## Recommendation

The actual slippage protection as can be found in the official UniV3-periphery `LiquidityManagement.addLiquidity` should use the return values of `UniswapV3Pool.mint` and check against the slippage input params like this:

```js
(amount0, amount1) = pool.mint(
    params.recipient,
    params.tickLower,
    params.tickUpper,
    liquidity,
    abi.encode(MintCallbackData({poolKey: poolKey, payer: msg.sender}))
);

require(amount0 >= params.amount0Min && amount1 >= params.amount1Min, 'Price slippage check');
```

**Comment by eliteWalrus4164** [comment]
Escalate

I might be missing something, but it seems that all of these issues are somewhat invalid, except for the issue #105 submitted by my team. Gathered my rebutals here, I think it will be simpler to discuss:

#180 : A Multipool manages multiple different ranges on UniswapV3, it is not possible to use the single position mint slippage formula as suggested in remediation. 
Checking the amounts to be pulled in accross all ranges with a function such as `_optimizeAmount`, and check they are not below minAmount0 and minAmount1 is the correct way to do it (since it guarantees that the mint is done around a given price).

https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L793-L797
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L799-L805

This allows a user to check that providing liquidity is done around a given price.
If the underlying pool is imbalanced, the amount of token to be pulled on one side would be lower, and the function would revert.  

#61 : Is talking about slippage in a swap, it is not related to depositing

#68 : The poc demonstrates a negligible loss (few wei), probably due to a rounding error

#117 : See #180, slippage is correctly checked for the deposit function, there is no need to check it for the low-level call since the pool would not be deviated. If the user deviates the pool himself, he is minting less for providing more tokens, and only harms himself

#119 : Very vague issue, mentioning swaps as well?
> But there are no checks to ensure the minimum amount of tokens are collected during the swap.

This is false since this is checked in `_optimizeAmounts`

#144: This one, although more precise misses the fact that in each of the cases, both slippage amounts are checked implicitly:

In this case:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L792-L797
the amount0 used is amount0Desired, and thus is implicitly >= amount0Min

In this case:
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L798-L806
the amount1 used is amount1Desired and thus is implicitly >= amount1Min

#185: This one is also more sophisticated, but misses the fact that a large donation to the pool is necessary:
> Attacker transfers 4,000 USDC to the RealWagmi contract

Which makes the attack unprofitable to the potential attacker

#105: This issue is valid: This is the only case in which the `_optimizeAmounts` check fails: `when multiple feeTiers are available`. This is because multiple pools may be imbalanced in opposite directions, and thus the ratio of tokens may remain the same, but the user has to provide more tokens as an input (minting inefficiently accross multiple pools).

**Comment by sherlock-admin** [comment]
> Escalate
> 
> I might be missing something, but it seems that all of these issues are somewhat invalid, except for the issue #105 submitted by my team. Gathered my rebutals here, I think it will be simpler to discuss:
> 
> #180 : A Multipool manages multiple different ranges on UniswapV3, it is not possible to use the single position mint slippage formula as suggested in remediation. 
> Checking the amounts to be pulled in accross all ranges with a function such as `_optimizeAmount`, and check they are not below minAmount0 and minAmount1 is the correct way to do it (since it guarantees that the mint is done around a given price).
> 
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L793-L797
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L799-L805
> 
> This allows a user to check that providing liquidity is done around a given price.
> If the underlying pool is imbalanced, the amount of token to be pulled on one side would be lower, and the function would revert.  
> 
> #61 : Is talking about slippage in a swap, it is not related to depositing
> 
> #68 : The poc demonstrates a negligible loss (few wei), probably due to a rounding error
> 
> #117 : See #180, slippage is correctly checked for the deposit function, there is no need to check it for the low-level call since the pool would not be deviated. If the user deviates the pool himself, he is minting less for providing more tokens, and only harms himself
> 
> #119 : Very vague issue, mentioning swaps as well?
> > But there are no checks to ensure the minimum amount of tokens are collected during the swap.
> 
> This is false since this is checked in `_optimizeAmounts`
> 
> #144: This one, although more precise misses the fact that in each of the cases, both slippage amounts are checked implicitly:
> 
> In this case:
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L792-L797
> the amount0 used is amount0Desired, and thus is implicitly >= amount0Min
> 
> In this case:
> https://github.com/sherlock-audit/2023-06-real-wagmi/blob/main/concentrator/contracts/Multipool.sol#L798-L806
> the amount1 used is amount1Desired and thus is implicitly >= amount1Min
> 
> #185: This one is also more sophisticated, but misses the fact that a large donation to the pool is necessary:
> > Attacker transfers 4,000 USDC to the RealWagmi contract
> 
> Which makes the attack unprofitable to the potential attacker
> 
> #105: This issue is valid: This is the only case in which the `_optimizeAmounts` check fails: `when multiple feeTiers are available`. This is because multiple pools may be imbalanced in opposite directions, and thus the ratio of tokens may remain the same, but the user has to provide more tokens as an input (minting inefficiently accross multiple pools).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by talfao** [comment]
In my report #68 , I just show that some loss is done. However, the main point is about missing slippage protection which does not protect from minting lp tokens from the Uniswap pool. The resource I specify in my report generally says that after minting lp tokens, there should be a check if some minAmount is kept (same as in this report) . This is not done, and the loss could also be more significant. 

This report (similar to mine) should be valid.

**Comment by fann95** [comment]
We simplified the slip check and added the minimum acceptable amount of liquidity tokens to be minted. https://github.com/RealWagmi/concentrator/blob/fbccf1caf28edbb23db8c7e0409d0c40c3a56461/contracts/Multipool.sol#L415C19-L415C19

**Comment by ctf-sec** [comment]
I agree #61 is not a duplicate of this issue,

but for the rest of the report,

as long as they mention the missing slippage when minting

**Comment by eliteWalrus4164** [comment]
@ctf-sec the slippage protection implemented in _optimizeAmounts works correctly (except for the case described in #105):
https://github.com/sherlock-audit/2023-06-real-wagmi/blob/82a234a5c2c1fc1921c63265a9349b71d84675c4/concentrator/contracts/Multipool.sol#L780-L808

The fix of checking a minimum amount of tokens minted is simpler but is redundant with regards to what is described in this report

**Comment by talfao** [comment]
The uniswap itself recommends that the slippage should be checked **after** minting. 
https://uniswapv3book.com/docs/milestone_3/slippage-protection/

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates 
Agree with the above escalations regarding the validity of all the issues. 
This is not a valid issue since slippage protection works correctly when one fee tier is involved.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [crimson-rat-reach](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/180/#issuecomment-1634309712): accepted
