### ISSUE TITLE
Bauchibred - Uniswap oracle should not be used on L2s

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-real-wagmi-judging#55]
Bauchibred

medium

# Uniswap oracle should not be used on L2s

## Summary

RealWagmi is planned to be deployed on multiple Layer 2 (L2) networks. However, it is important to note that Uniswap advises against using their oracle on L2 networks, including Optimism and Arbitrum, due to the ease of manipulating price feeds in these environments. Therefore, it is recommended to refrain from utilizing Uniswap's oracle feature on Arbitrum until further updates or improvements are made to enhance oracle security.

## Vulnerability Detail

The information provided by the Uniswap team, as documented in the [Uniswap Oracle Integration on Layer 2 Rollups](https://docs.uniswap.org/concepts/protocol/oracle#oracles-integrations-on-layer-2-rollups) guide, primarily addresses the integration of Uniswap oracle on L2 Optimism. However, it is relevant to note that the same concerns apply to Arbitrum as well. Arbitrum's average block time is approximately 0.25 seconds, making it vulnerable to potential oracle price manipulation.

> ### Oracles Integrations on Layer 2 Rollups
>
> Optimism
> On Optimism, every transaction is confirmed as an individual block. The block.timestamp of these blocks, however, reflect the block.timestamp of the last L1 block ingested by the Sequencer. For this reason, Uniswap pools on Optimism are not suitable for providing oracle prices, as this high-latency block.timestamp update process makes the oracle much less costly to manipulate. In the future, it's possible that the Optimism block.timestamp will have much higher granularity (with a small trust assumption in the Sequencer), or that forced inclusion transactions will improve oracle security. For more information on these potential upcoming changes, please see the [Optimistic Specs repo](https://github.com/ethereum-optimism/optimistic-specs/discussions/23). **For the time being, usage of the oracle feature on Optimism should be avoided.**

## Impact

Easily Manipulated Oracle Data

## Code Snippet

https://github.com/sherlock-audit/2023-06-real-wagmi/blob/82a234a5c2c1fc1921c63265a9349b71d84675c4/concentrator/contracts/Factory.sol#L3

## Tool used

Manual Audit

## Recommendation

Until further updates or improvements are made to address the security concerns associated with Uniswap's oracle on Arbitrum, it is strongly recommended to refrain from utilizing the oracle feature in the current implementation.

**Comment by Bauchibred** [comment]
Escalate

> Q: On what chains are the smart contracts going to be deployed? Fantom, Arbitrum, ZKera, Polygon, Binance Smart Chain, KAVA
>
> In the contest onchain readme,
>
> there is no optimism network
>
> so that is why I excluded the issue, severity is low :)

While I agree that the contest on-chain readme did not list Optimism, I would like to indicate that the vulnerability associated with high-latency timestamps in Oracle price feeds, identified in my report, is applicable beyond just Optimism—it impacts Arbitrum too, I included both of them to make the report whole and the severity of this issue should not be underestimated.

> The docs
>
> [Uniswap Oracle Integration on Layer 2 Rollups](https://docs.uniswap.org/concepts/protocol/oracle#oracles-integrations-on-layer-2-rollups)
>
> does not mention Arbitrum

This is also valid, but the fact that the Uniswap Oracle Integration documentation doesn't explicitly mention Arbitrum, does not mean the issue at hand doesn't affect it. Both Arbitrum and Optimism use Optimistic Rollups, as I understand it In such a framework, each Layer 2 transaction is regarded as a separate block, yet the timestamps of these blocks reflect the timestamp of the most recent Layer 1 block acknowledged by the sequencer.

Given that Layer 1 blocks are produced less frequently than Layer 2 transactions, a delay or "high latency" as referred to in the [Uniswap Oracle docs](https://docs.uniswap.org/concepts/protocol/oracle#oracles-integrations-on-layer-2-rollups), arises in timestamp updates. This delay results in a scenario where multiple Layer 2 blocks can share the same timestamp until the next Layer 1 block is processed. This situation makes the oracle price feeds on the L2 easier to manipulate, i.e the root cause of this issue is thus deeply rooted in the Optimistic Rollups technology utilized by both Arbitrum and Optimism, quoting this section of the [Arbitrum's docs](https://developer.arbitrum.io/for-devs/troubleshooting-building#how-do-blocktimestamp-and-blocknumber-work-on-arbitrum) below

> Solidity calls to block.number and block.timestamp on Arbitrum will return the block number/ timestamp of the underlying L1 on a slight delay; i.e., updated every few minutes. Note that L2 block numbers (i.e., as seen in block explorers / returned by RPCs) are different, and are typically updated roughly every second.

As seen implications of this vulnerability extend beyond the specific layer 2 network _optimism_ mentioned in Uniswap's documentation, but more of those that use optimistic rollups.

**Comment by sherlock-admin** [comment]
> 
> 
> Escalate
> 
> > Q: On what chains are the smart contracts going to be deployed? Fantom, Arbitrum, ZKera, Polygon, Binance Smart Chain, KAVA
> >
> > In the contest onchain readme,
> >
> > there is no optimism network
> >
> > so that is why I excluded the issue, severity is low :)
> 
> While I agree that the contest on-chain readme did not list Optimism, I would like to indicate that the vulnerability associated with high-latency timestamps in Oracle price feeds, identified in my report, is applicable beyond just Optimism—it impacts Arbitrum too, I included both of them to make the report whole and the severity of this issue should not be underestimated.
> 
> > The docs
> >
> > [Uniswap Oracle Integration on Layer 2 Rollups](https://docs.uniswap.org/concepts/protocol/oracle#oracles-integrations-on-layer-2-rollups)
> >
> > does not mention Arbitrum
> 
> This is also valid, but the fact that the Uniswap Oracle Integration documentation doesn't explicitly mention Arbitrum, does not mean the issue at hand doesn't affect it. Both Arbitrum and Optimism use Optimistic Rollups, as I understand it In such a framework, each Layer 2 transaction is regarded as a separate block, yet the timestamps of these blocks reflect the timestamp of the most recent Layer 1 block acknowledged by the sequencer.
> 
> Given that Layer 1 blocks are produced less frequently than Layer 2 transactions, a delay or "high latency" as referred to in the [Uniswap Oracle docs](https://docs.uniswap.org/concepts/protocol/oracle#oracles-integrations-on-layer-2-rollups), arises in timestamp updates. This delay results in a scenario where multiple Layer 2 blocks can share the same timestamp until the next Layer 1 block is processed. This situation makes the oracle price feeds on the L2 easier to manipulate, i.e the root cause of this issue is thus deeply rooted in the Optimistic Rollups technology utilized by both Arbitrum and Optimism, quoting this section of the [Arbitrum's docs](https://developer.arbitrum.io/for-devs/troubleshooting-building#how-do-blocktimestamp-and-blocknumber-work-on-arbitrum) below
> 
> > Solidity calls to block.number and block.timestamp on Arbitrum will return the block number/ timestamp of the underlying L1 on a slight delay; i.e., updated every few minutes. Note that L2 block numbers (i.e., as seen in block explorers / returned by RPCs) are different, and are typically updated roughly every second.
> 
> As seen implications of this vulnerability extend beyond the specific layer 2 network _optimism_ mentioned in Uniswap's documentation, but more of those that use optimistic rollups.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
See https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/51

the admin can set the TWAP period and the longer the TWAP parameter, the harder for attacker to manipulate the oracle, recommend maintain low severity

**Comment by hrishibhat** [comment]
@Bauchibred do you have additional comments?

**Comment by Bauchibred** [comment]
@hrishibhat, with due respect to the the lead judge's expertise I have to disagree with his stance  on this issue. 

Based on this [comment](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/55#issuecomment-1646249485):
>See https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/51
the admin can set the TWAP period and the longer the TWAP parameter, the harder for attacker to manipulate the oracle, recommend maintain low severity

Lead judge's new reason for keeping this issue a low is the fact that admin could set the _TWAP parameter longer_, but imo the admin setting the twap period longer in order to curb this makes RealWagmi easily vulnerable to new attack windows, how long is admin going to set it? for some tokens even 30 minutes could be considered too long, since the price would now diverge from the real price frequently due to market conditions.


Additionally as stated by lead judge in the attached comment, even if the admin sets the twap parameter longer, it makes the attack harder, but it doesn't stop the attack, so issue still exists, why? Because the root cause of the issue is attached to implementing Uniswap oracles on L2s and not how long the twap parameter could be.

With these points I believe that issue is still a valid medium.

**Comment by hrishibhat** [comment]
@Bauchibred Artibtrum should have their own block numbers and i don't think it has the underlying problem of optimism. 
https://docs.arbitrum.io/time#arbitrum-block-numbers
I still think this should be an informational issue.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low issue based on the above discussion.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Bauchibred](https://github.com/sherlock-audit/2023-06-real-wagmi-judging/issues/55/#issuecomment-1635599585): rejected
